HW_4_partialy!!!
olexey81/HomeWorksOld pull request #4
Opened 2023-06-10 17:23 UTC by olexey81

Завдання 1,2 повністю, по завданню на структури прошу подивитися, зробив першу функцію для List, чи правильно я зрозумів на рахунок object, що фактично будуть структури не типизовані?

2023-06-11 09:16 UTC, Delvin09 requested changes
Так, структури будуть нетипові. Окрім Дерева, там інт.

2023-06-11 09:16 UTC, Delvin09 commented on HW_4_Repka/CharachtersNames.cs
> +    {
англійський будь ласка. Це ж не стрінгові літерали.

2023-06-11 09:16 UTC, Delvin09 commented on HW_4_Repka/Program.cs
> +        {
Чому б не створити клас Казка, який інкапсулюватиме все, що стосується конкретної казки?

2023-06-11 09:16 UTC, Delvin09 commented on HW_4_Bank/Money.cs
> +        private readonly decimal _Money;
трохи не так, я припускав, що тут будуть два цілих, одне відповідає за банкноти, друге за копійки.

2023-06-12 06:22 UTC, olexey81 commented on HW_4_Bank/Money.cs
> +        private readonly decimal _Money;
змінив для Money, але залишив для виводу суми (транзакціїї та відображення суми на рахунку)

2023-06-13 15:22 UTC, olexey81 commented
Добрий день! Перевірьте будь ласка.

2023-06-15 09:31 UTC, Delvin09 requested changes

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Repka/Charachter.cs
> +        public bool IsPulledPlant(Plant plant)
У нас лише один персонаж може посадити ріпку.

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Bank/Client.cs
> +        public List<Account> Accounts { get; }
Можна змінити перелік рахунків в обхід банку.

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Bank/Client.cs
> +        public List<Account> Accounts { get; }
Є подібні проблеми в інших місцях.

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/LinkedList.cs
> +        public new void Add(object data)
Ні. Потрібно без нового. У тебе методи досить схожі, подумай, як можна їх оверрайднути.

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/LinkedList.cs
> +        private LinkedNode _first;
_first та _last у тебе вже є

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            if (index >= _size)
Можна оптимізувати вставку та видалення в кінці

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            if (_size < _items.Length)
Я написав би так (коду менше):
`if (_size >= _items.Length)`
`   ExtendArray();`
`AddToEnd(newItem);`

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            for (int i = 0; i < _size; i++)
чому б не використовувати IndexOf для цього?

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            object[] _itemsExtend = new object[Capacity + _InitCapacity * 2];
я правильно розумію, що у тебе внутрішній масив завжди виростає на 8 елементів?

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            object[] _itemsMod;
не зовсім розумію, навіщо створювати новий масив для вставки. тобто. для ситуації коли не вистачає ємності – це виправдано. Чому б просто не зрушити всі елементи, починаючи з індексу вставки, праворуч? (краще починати обхід із кінця)

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +                    _itemsCompressed[i] = _items[i + 1];
якщо Capacity - _size == 0, я думаю, тут буде помилка.

2023-06-15 09:31 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            object[] _itemsCompressed;
Загалом я не бачу сенсу у такому стисканні. У Списку з .NET немає такої поведінки. Стиснення відбувається лише при зміні Капасіті. При постійному стиску при видаленні елементів, це буде погано позначатися на продуктивності.

2023-06-15 13:44 UTC, olexey81 commented on HW_4_Bank/Client.cs
> +        public List<Account> Accounts { get; }
Зі обмеженням доступу через інтерфейси/абстракцію не зовсям розібрався.
Можна буде якось взагалі на ці теми більш подробно розібрати на занятті?

2023-06-15 13:52 UTC, olexey81 commented on HW_4_Collections/List.cs
> +            for (int i = 0; i < _size; i++)
public bool Contains(object item)
        {
            if (IndexOf(item) > -1)
                    return true;
            return false;
        }

2023-06-15 13:54 UTC, olexey81 commented on HW_4_Collections/List.cs
> +            object[] _itemsExtend = new object[Capacity + _InitCapacity * 2];
так, вирішив на подвійне значення від початкового, щоб не дуже великий розмір був. але звісно можна наприклад кожного разу вдвічі збільшувати.

2023-06-15 14:04 UTC, olexey81 commented on HW_4_Collections/List.cs
> +            object[] _itemsMod;
private void ModArrayToInsert(int index)
        {
            if (_size == Capacity)
            {
                object[] _itemsMod;
                _itemsMod = new object[Capacity + _InitCapacity];
                for (int i = 0; i < _size; i++)
                {
                    if (i < index)
                        _itemsMod[i] = _items[i];
                    else
                        _itemsMod[i + 1] = _items[i];
                }
                _items = _itemsMod;
            }    
            else
                for (int i = _size; i > index; i--)
                    _items[i] = _items[i - 1];
        }

2023-06-15 14:05 UTC, olexey81 commented on HW_4_Collections/List.cs
> +            object[] _itemsCompressed;
З власної ініціативи ) Прибрав стиснення

2023-06-15 14:25 UTC, olexey81 commented on HW_4_Collections/List.cs
> +            object[] _itemsCompressed;
private void CompressArray(int index)
        {
            for (int i = index; i < _size; i++)
                    _items[i] = _items[i + 1];
            _size--;
        }

2023-06-17 15:43 UTC, olexey81 commented
17.06

2023-06-17 15:43 UTC, merged

2023-06-18 18:10 UTC, Delvin09 commented on HW_4_Collections/List.cs
> +            for (int i = 0; i < _size; i++)
return IndexOf(item) > -1;