HW_5 23-06-2023
olexey81/HomeWorksOld pull request #7
Opened 2023-06-23 14:52 UTC by olexey81

З пріритетною чергою розібрався, переробив набагато простіше.
Ніби то нічого з переліку завдань не пропустив )
По пошуку - заюзав бинарний та на сортування merge sort

2023-06-24 13:25 UTC, Delvin09 requested changes

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/InterfacesObject/IMyList.cs
> +        bool Contains(object value);
Contains теж можна давати в ICollection, а для дерева залишити bool Contains (int value);
У дженерик версії інтерфейсів такої проблеми не повинно бути.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/InterfacesObject/IMyList.cs
> +    interface IMyList : IMyCollection
Ці інтерфейси варто зробити публічними

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyList.cs
> +                int comparisonResult = Comparer<object>.Default.Compare(_items[middle], item);
Ще можна передавити компаратор методом, через лямбду чи об'єкт IComparer. А Comparer<object>.Default залишити якщо нічого не було передане.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyList.cs
> +                    return BinarySearch(item, left, middle - 1);
Ок, але рекурсивна реалізація бінарного пошуку не є такою ефективною. Можеш не переписувати.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyList.cs
> +        private void MergeSort(object[] arr, int left, int right)
Такі самі зауваження як і до бінарного пошуку.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyLinkedList.cs
> +        private LinkedNode? _first;
Поля та властивості у тебе вже є на базовому рівні.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyLinkedList.cs
> +        private LinkedNode? _first;
А вирішити проблему з різними типами нодів можна так:
![image](https://github.com/olexey81/HomeWorks/assets/29715723/29e6d483-b4fc-4de2-8ac0-5a9d17d3f274)
===========================================
![image](https://github.com/olexey81/HomeWorks/assets/29715723/3a1aa13a-db13-4d3c-890a-a2d39f7fcc7a)

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyQueue.cs
> +        public IEnumerator GetEnumerator() => new QueueIterator(_items);
Тут можна було б перевикористовувати ітератор Ліста. Просто:

![image](https://github.com/olexey81/HomeWorks/assets/29715723/f158d76b-97dd-4187-ad63-7ea4955d0b11)

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyStack.cs
> +        private class StackIterator : IEnumerator
Ітератор стека повинен оминати елементи з кінця списку. Тобто. у логіці стека.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyBinarySearchTree.cs
> +            MyList array = new MyList(_size);
Можна відразу в масив, Count вже відомий.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyBinarySearchTree.cs
> +        //public IEnumerator GetEnumerator()
без List, IEnumerator не повинен створювати колекції. Мається на увазі повну копію колекції, допоміжні колекції та змінні можна створювати.
yield можно использовать в рекурсивном обходе дерева.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyBinarySearchTree.cs
> +                _tree = tree.ToArray();
Те ж саме, що і для yield версії вище.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyBinarySearchTree.cs
> +                _tree = tree.ToArray();
Обхід дерева через ітератор може бути складнішим, ніж здається. Зазвичай для цього використовують стек. Наприклад:

```
public bool MoveNext()
        {
            if (nodesStack.Count <= 0)
                return false;

            var current = nodesStack.Peek();
            do
            {
                switch (current.State)
                {
                    case EnumState.Left:
                        if (current.Node.Left != null)
                            nodesStack.Push(new Container(current.Node.Left));
                        current.State = EnumState.Right;
                        current = nodesStack.Peek();
                        break;
                    case EnumState.Right:
                        nodesStack.Pop();
                        if (current.Node.Right != null)
                            nodesStack.Push(new Container(current.Node.Right));
                        if (nodesStack.Count <= 0)
                            return false;
                        current = nodesStack.Peek();
                        break;
                }
            } while (current.State == EnumState.Left);

            return true;
        }
```

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyList.cs
> +        public T Search(T item)
?

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyList.cs
> +        public T Search(T item)
Не бачу реалізації

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyOneLinkedList.cs
> +    internal class MyOneLinkedList<T> : IMyLinkedLists<T> where T : IComparable<T>
Не дуже правильно обмежувати тип списку, тому що він за логікою може зберігати все, що завгодно. Потрібно знайти інший спосіб порівняння елементів у сортуванні та пошуку.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyOneLinkedList.cs
> +                Current = (T)_currentNode.Data;
(Т) - немає потреби

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyObservableList.cs
> +        public event Action<T> ItemAdded;
Добре, але подія/події повинні відбуватися при кожній зміні списку.

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/ExtensionMethods/MyLINQ.cs
> +                _iter.Reset();
Тоді і _count потрібно обнулити

2023-06-24 13:25 UTC, Delvin09 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/ExtensionMethods/MyLINQ.cs
> +        class TakeWhileIterator : IEnumerator
Take і TakeWhile ітератори можна поєднати в один універсальний ітератор. Теж саме і для Skip i SkipWhile

2023-06-25 10:04 UTC, olexey81 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/InterfacesObject/IMyList.cs
> +        bool Contains(object value);
так а якщо в ICollection в мене  bool Contains(object value);, потім я спадкуюсь в IMyBinarySearchTree, де в мене буде для дерева  bool Contains (int value), то в самому класі помилка имплементаціїї object , як виключити контракт на object ? власно тому і розкидав через дерево.
По дженерикам виправив

2023-06-26 07:12 UTC, olexey81 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsObject/MyList.cs
> +                int comparisonResult = Comparer<object>.Default.Compare(_items[middle], item);
Можна буде подробно це на занятті пояснити?

2023-06-26 08:18 UTC, olexey81 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/CollectionsGeneric/MyList.cs
> +        public T Search(T item)
мм, зайве мабуть залишилось, видалив, так як MyBinarySearch реалізований у всіх списках

2023-06-26 10:02 UTC, olexey81 commented on HW_5_Generic_LINQ/HW_5_Generic_LINQ/ExtensionMethods/MyLINQ.cs
> +                _iter.Reset();
прибрав взагалі реалізації резет та диспоуз

2023-06-26 10:10 UTC, olexey81 commented
З компараторами можна пояснення на зантті? Або якесь джерело з подробними роз'ясненнями?

2023-06-26 10:11 UTC, olexey81 commented
З компараторами можна пояснення на занятті? Або якесь джерело з подробними роз'ясненнями?

2023-06-27 14:58 UTC, merged